/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PemrogrammanVisual;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author reki.pebriana
 */
public class nilai extends javax.swing.JFrame {

    /**
     * Creates new form nilai
     */
    public nilai() {
        initComponents();
        lulus.setVisible(false);
        gagal.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg21 = new PemrogrammanVisual.bg2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuts = new javax.swing.JTextField();
        ttugas = new javax.swing.JTextField();
        tuas = new javax.swing.JTextField();
        cmdclear = new javax.swing.JButton();
        cmdhitung = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lakhir = new javax.swing.JLabel();
        lulus = new javax.swing.JLabel();
        lgrade = new javax.swing.JLabel();
        gagal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nilai Tugas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nilai UTS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nilai UAS");

        tuts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tuts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tutsKeyPressed(evt);
            }
        });

        ttugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ttugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ttugasKeyPressed(evt);
            }
        });

        tuas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tuas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tuasKeyPressed(evt);
            }
        });

        cmdclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdclear.setText("Clear");
        cmdclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdclearActionPerformed(evt);
            }
        });

        cmdhitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdhitung.setText("Hitung Nilai");
        cmdhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhitungActionPerformed(evt);
            }
        });
        cmdhitung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdhitungKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lakhir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lakhir.setForeground(new java.awt.Color(153, 153, 255));
        lakhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lakhir.setText("Nilai Akhir");
        jPanel1.add(lakhir);
        lakhir.setBounds(22, 17, 150, 25);

        lulus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/senang.jpg"))); // NOI18N
        jPanel1.add(lulus);
        lulus.setBounds(20, 80, 149, 115);

        lgrade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lgrade.setForeground(new java.awt.Color(153, 102, 0));
        lgrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgrade.setText("Grade");
        jPanel1.add(lgrade);
        lgrade.setBounds(22, 48, 150, 16);

        gagal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sedih.jpg"))); // NOI18N
        gagal.setText("jLabel6");
        jPanel1.add(gagal);
        gagal.setBounds(20, 80, 136, 115);

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(ttugas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(43, 43, 43)
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tuts, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(tuas)))))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdhitung)
                        .addGap(18, 18, 18)
                        .addComponent(cmdclear)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdclear)
                    .addComponent(cmdhitung))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bg21Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhitungActionPerformed
        // TODO add your handling code here:

        int tugas = Integer.parseInt(ttugas.getText());
        int uts = Integer.parseInt(tuts.getText());
        int uas = Integer.parseInt(tuas.getText());

        double akhir = 0.2 * tugas + 0.3 * uts + 0.5 * uas;
        lakhir.setText("Nilai : " + akhir);

        if (akhir >= 88) {
            lgrade.setText("Grade : A");
            lulus.setVisible(true);
            gagal.setVisible(false);
        } else if (akhir >= 74) {
            lgrade.setText("Grade : B");
            lulus.setVisible(true);
            gagal.setVisible(false);
        } else if (akhir >= 56) {
            lgrade.setText("Grade : C");
            lulus.setVisible(true);
            gagal.setVisible(false);
        } else if (akhir >= 45) {
            lgrade.setText("Grade : D");
            lulus.setVisible(false);
            gagal.setVisible(true);
        } else {
            lgrade.setText("Grade : E");
            lulus.setVisible(false);
            gagal.setVisible(true);

        }

    }//GEN-LAST:event_cmdhitungActionPerformed

    private void cmdhitungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdhitungKeyPressed
        // TODO add your handling code here:

        int kode = evt.getKeyCode();
        if (kode == evt.VK_ENTER) {
            int tugas = Integer.parseInt(ttugas.getText());
            int uts = Integer.parseInt(tuts.getText());
            int uas = Integer.parseInt(tuas.getText());

            double akhir = 0.2 * tugas + 0.3 * uts + 0.5 * uas;
            lakhir.setText("Nilai : " + akhir);
            if (akhir >= 88) {
                lgrade.setText("Grade : A");
                lulus.setVisible(true);
                gagal.setVisible(false);
            } else if (akhir >= 74) {
                lgrade.setText("Grade : B");
                lulus.setVisible(true);
                gagal.setVisible(false);
            } else if (akhir >= 56) {
                lgrade.setText("Grade : C");
                lulus.setVisible(true);
                gagal.setVisible(false);
            } else if (akhir >= 45) {
                lgrade.setText("Grade : D");
                lulus.setVisible(false);
                gagal.setVisible(true);
            } else {
                lgrade.setText("Grade : E");
                lulus.setVisible(false);
                gagal.setVisible(true);

            }

        }
    }//GEN-LAST:event_cmdhitungKeyPressed

    private void cmdclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdclearActionPerformed
        // TODO add your handling code here:
        ttugas.setText("");
        tuts.setText("");
        tuas.setText("");
        lakhir.setText("");
        lgrade.setText("");
        lulus.setVisible(false);
        gagal.setVisible(false);
        ttugas.requestFocus();
    }//GEN-LAST:event_cmdclearActionPerformed

    private void ttugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttugasKeyPressed
        // TODO add your handling code here:
        int kode = evt.getKeyCode();
        if (kode == evt.VK_ENTER) {
            tuts.requestFocus();
        }
    }//GEN-LAST:event_ttugasKeyPressed

    private void tutsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tutsKeyPressed
        // TODO add your handling code here:
        int kode = evt.getKeyCode();
        if (kode == evt.VK_ENTER) {
            tuas.requestFocus();
        }
    }//GEN-LAST:event_tutsKeyPressed

    private void tuasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuasKeyPressed
        // TODO add your handling code here:
        int kode = evt.getKeyCode();
        if (kode == evt.VK_ENTER) {
            cmdhitung.requestFocus();
        }
    }//GEN-LAST:event_tuasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PemrogrammanVisual.bg2 bg21;
    private javax.swing.JButton cmdclear;
    private javax.swing.JButton cmdhitung;
    private javax.swing.JLabel gagal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lakhir;
    private javax.swing.JLabel lgrade;
    private javax.swing.JLabel lulus;
    private javax.swing.JTextField ttugas;
    private javax.swing.JTextField tuas;
    private javax.swing.JTextField tuts;
    // End of variables declaration//GEN-END:variables
}
